alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: ${PUBLIC_DOMAIN}
    type: PRIMARY
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: nextjs-app
      match:
        path:
          prefix: /
name: production-env
region: fra
services:
  - envs:
      - key: SUPABASE_URL
        scope: RUN_TIME
        value: ${SUPABASE_URL}
      - key: SUPABASE_ANON_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${SUPABASE_ANON_KEY}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${OPENAI_API_KEY}
    http_port: 3000
    image:
      registry_type: GHCR
      registry: ${OWNER}
      registry_credentials: ${OWNER}:${GHCR_TOKEN}
      repository: listock
      tag: ${TAG}
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: nextjs-app
